### ISSUE TITLE
File with Exact Architecture

### ISSUE THREAD

**Issue by Shashi456** [bert-nmt/bert-nmt#13]
Hello,
I've been trying to locate the file with the exact bert fused nmt architecture, could you please mention the name? 
Thanks a lot for the clarification.

**Comment by teslacool** [comment]
Hi,

The file defining the architecture is fairseq/models/transformer.py. 

We register the model at [line](https://github.com/bert-nmt/bert-nmt/blob/cd79c1d3cd387652a407d3ecf0a4a4fda92b95a0/fairseq/models/transformer.py#L175).

We register the arch at [line](https://github.com/bert-nmt/bert-nmt/blob/cd79c1d3cd387652a407d3ecf0a4a4fda92b95a0/fairseq/models/transformer.py#L1983).

**Comment by Shashi456** [comment]
@teslacool thank you.
