### ISSUE TITLE
Is there a memory leak in the code?

### ISSUE THREAD

**Issue by nomadlx** [bert-nmt/bert-nmt#14]
I got the error ”Exception: process 1 terminated with signal SIGKILL“ when i training a model(25M sentences). It seem that caused by out of memory, the reason as follow:

- This error appear after "loading train data" and "saved checkpoint", so i think It should be during training.
- It's not GPU OOM
- Memory usage continue to increase during this period
- It run well when i train in a small dataset(4k sentences) with same parameters, but i just try train 5 epoch.

**Comment by teslacool** [comment]
Hi, can you paste your full error message?

I did not encounter this error.

**Comment by nomadlx** [comment]
I am back. This error is caused by a lack of memory，because i used a 20 million leval train data and fairseq read whole train data at once before start training. I had sloved this error by setting lazy mode to load data.
