### ISSUE TITLE
num_updates

### ISSUE THREAD

**Issue by sdlmw** [bert-nmt/bert-nmt#15]
Hi @bert-nmt  
How did this error cause it, and if modified, what parameters should I add?

 File "train.py", line 167
    progress.print(stats, tag='train', step=stats['num_updates'])

thanks

**Comment by teslacool** [comment]
Hi, can you paste the full error message?

**Comment by sdlmw** [comment]
@teslacool   yes,

this is the command.
`
cd /MT-work/bert-nmt
src=en
tgt=zh
bedropout=0.5
ARCH=transformer_wmt_en_de
DATAPATH=/MT-work/Corpus/en-US_zh-CN/200319
SAVEDIR=/MT-work/Corpus/en-US_zh-CN/200319/checkpoints/
mkdir -p $SAVEDIR
if [ ! -f $SAVEDIR/checkpoint_nmt.pt ]
then
    cp /MT-work/bert-nmt/checkpoints/checkpoint_best.pt $SAVEDIR/checkpoint_nmt.pt
fi
if [ ! -f "$SAVEDIR/checkpoint_last.pt" ]
then
warmup="--warmup-from-nmt --reset-lr-scheduler"
else
warmup=""
fi

python train.py $DATAPATH \
-a $ARCH --optimizer adam --lr 0.0005 -s $src -t $tgt --label-smoothing 0.1 \
--dropout 0.3 --max-tokens 4000 --min-lr '1e-09' --lr-scheduler inverse_sqrt --weight-decay 0.0001 \
--criterion label_smoothed_cross_entropy --max-update 150000 --warmup-updates 4000 --warmup-init-lr '1e-07' \
--adam-betas '(0.9,0.98)' --save-dir $SAVEDIR --share-all-embeddings $warmup \
--encoder-bert-dropout --encoder-bert-dropout-ratio $bedropout --num_updates 20676 | tee -a $SAVEDIR/training.log`

There's only one error.
`mingwei@bert:/MT-work/Corpus/en-US_zh-CN/200319$ bash TrainCommand.sh
  File "train.py", line 167
    progress.print(stats, tag='train', step=stats['num_updates'])
                 ^
SyntaxError: invalid syntax
`
Thank you!

**Comment by teslacool** [comment]
@sdlmw Hi, I do not think this line could produce any error and I can not reproduce your error.  This may be wrong in other nearby lines. I suggest you use debug mode in PyCharm to locate error.

**Comment by sdlmw** [comment]
@teslacool ，alright，i will check

**Comment by teslacool** [comment]
@sdlmw  Ok, feel free to communicate.

**Comment by haorannlp** [comment]
> Hi @bert-nmt
> How did this error cause it, and if modified, what parameters should I add?
> 
> File "train.py", line 167
> progress.print(stats, tag='train', step=stats['num_updates'])
> 
> thanks

Hi, did you solve the problem?

**Comment by teslacool** [comment]
@haorannlp Hi, can you paste more log? I can not see any useful information from this snippet.

**Comment by RMisha101** [comment]
> > Hi @bert-nmt
> > How did this error cause it, and if modified, what parameters should I add?
> > File "train.py", line 167
> > progress.print(stats, tag='train', step=stats['num_updates'])
> > thanks
> 
> Hi, did you solve the problem?

Tried updating the python version from 2 to 3?
