### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 7346: invalid continuation byte

### ISSUE THREAD

**Issue by echan00** [bert-nmt/bert-nmt#2]
I'm trying to follow the 'Data Preprocessing' example and am receiving a UTF-8 decoding error as shown below:

```
sudo python3 preprocess.py --source-lang en --target-lang de \
  --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
  --destdir data-bin/wmt17_en_de  --joined-dictionary --bert-model-name bert-base-multilingual-cased


Namespace(alignfile=None, bert_model_name='bert-base-multilingual-cased', cpu=False, criterion='cross_entropy', dataset_impl='cached', destdir='data-bin/wmt17_en_de', fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=True, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=False, optimizer='nag', padding_factor=8, seed=1, source_lang='en', srcdict=None, target_lang='de', task='translation', tbmf_wrapper=False, tensorboard_logdir='', testpref='examples/translation/wmt17_en_de/test', tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, trainpref='examples/translation/wmt17_en_de/train', user_dir=None, validpref='examples/translation/wmt17_en_de/valid', workers=1)
Traceback (most recent call last):
  File "preprocess.py", line 274, in <module>
    cli_main()
  File "preprocess.py", line 270, in cli_main
    main(args)
  File "preprocess.py", line 75, in main
    {train_path(lang) for lang in [args.source_lang, args.target_lang]}, src=True
  File "preprocess.py", line 56, in build_dictionary
    padding_factor=args.padding_factor,
  File "/bert-nmt/fairseq/tasks/fairseq_task.py", line 54, in build_dictionary
    Dictionary.add_file_to_dictionary(filename, d, tokenizer.tokenize_line, workers)
  File "/bert-nmt/fairseq/data/dictionary.py", line 284, in add_file_to_dictionary
    merge_result(Dictionary._add_file_to_dictionary_single_worker(filename, tokenize, dict.eos_word))
  File "/bert-nmt/fairseq/data/dictionary.py", line 262, in _add_file_to_dictionary_single_worker
    line = f.readline()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 7346: invalid continuation byte
```

My guess is because I am using the bert-base-multilingual-cased model?

Since I only care about EN and DE in this case:
I am changing line 247 in https://github.com/bert-nmt/bert-nmt/blob/master/fairseq/data/dictionary.py FROM:
`with open(filename, 'r', encoding='utf-8') as f:`
TO:
`with open(filename, 'r', encoding='utf-8', errors='ignore') as f:`

Does this sound correct?

**Comment by bert-nmt** [comment]
I think this error has nothing to do with Fairseq, but is related to your system variables.

And this step has also nothing to do with Bert model. This is only one `readline` function.

You can try `export LANG=C.UTF-8` or `export PYTHONIOENCODING=UTF-8`. The first method helped me solve similar errors in some docker.

**Comment by echan00** [comment]
I tried `export LANG=C.UTF-8` and `export PYTHONIOENCODING=UTF-8`, still no luck. I don't think it is the resolution since my system encoding is utf-8:
```
>>> import sys
>>> print(sys.getdefaultencoding())
utf-8
```

The error appears in both 'fairseq/binarizer.py' and 'fairseq/data/dictionary.py' 

I researched this problem on google, the problem is that the file being read contains invalid UTF-8. So in this case, this is either something in 'bert-base-multilingual-cased' or in the corpus data.

**Comment by echan00** [comment]
My guess is the issue is 'bert-base-multilingual-cased' because it is more likely to contain Asian characters that will cause the issue. The corpus data I am using is DE and EN from the repo (https://github.com/bert-nmt/bert-nmt/blob/master/examples/translation/prepare-wmt14en2de.sh)

**Comment by bert-nmt** [comment]
This bert model we use in data preprocessing is to act as a dictionary. If there is a problem in it, it should be an error when loading this vocab or indexing a word rather than loading the corpus. If you use `bert-base-uncased`, does this error also happen?

In our semi-supervised nmt task (en-ro), we use `bert-base-multilingual-cased`, and there is no error like yours.

We also suggest you to use `$MOSES/scripts/tokenizer/replace-unicode-punctuation.perl` and
`$MOSES/scripts/tokenizer/normalize-punctuation.perl` to clean your corpus.

**Comment by echan00** [comment]
Ended up using my own data set and didn't run into the problem anymore.
