### ISSUE TITLE
Please tell me how to use bin and idx files.

### ISSUE THREAD

**Issue by pdc-kaminaga** [bert-nmt/bert-nmt#20]
Hello,

Sorry to ask such a basic question.
I ran preprocess.py and I got bin and idx files.
I don't know how to use .bin and .idx files after this.
Please tell me how to use bin and idx files.

total 1687755
-rw------- 1 root root    534956 Apr 16 05:52 dict.de.txt
-rw------- 1 root root    534956 Apr 16 05:52 dict.en.txt
-rw------- 1 root root    324412 Apr 16 07:25 test.bert.en-de.en.bin
-rw------- 1 root root     72136 Apr 16 07:25 test.bert.en-de.en.idx
-rw------- 1 root root    338516 Apr 16 06:36 test.en-de.de.bin
-rw------- 1 root root     72136 Apr 16 06:36 test.en-de.de.idx
-rw------- 1 root root    324740 Apr 16 06:13 test.en-de.en.bin
-rw------- 1 root root     72136 Apr 16 06:13 test.en-de.en.idx
-rw------- 1 root root 479599392 Apr 16 07:24 train.bert.en-de.en.bin
-rw------- 1 root root  95068360 Apr 16 07:24 train.bert.en-de.en.idx
-rw------- 1 root root 477476928 Apr 16 06:36 train.en-de.de.bin
-rw------- 1 root root  95068360 Apr 16 06:36 train.en-de.de.idx
-rw------- 1 root root 466401152 Apr 16 06:13 train.en-de.en.bin
-rw------- 1 root root  95068360 Apr 16 06:13 train.en-de.en.idx
-rw------- 1 root root   4855892 Apr 16 07:25 valid.bert.en-de.en.bin
-rw------- 1 root root    961456 Apr 16 07:25 valid.bert.en-de.en.idx
-rw------- 1 root root   4838976 Apr 16 06:36 valid.en-de.de.bin
-rw------- 1 root root    961456 Apr 16 06:36 valid.en-de.de.idx
-rw------- 1 root root   4721140 Apr 16 06:13 valid.en-de.en.bin
-rw------- 1 root root    961456 Apr 16 06:13 valid.en-de.en.idx

**Comment by teslacool** [comment]
When you set `datapath` in [your training scripts](https://github.com/bert-nmt/bert-nmt#train-a-bert-fused-nmt-model), the code will use these files under directory  `datapath`.

**Comment by pdc-kaminaga** [comment]
Thanks to you, I could start train.py.
