### ISSUE TITLE
Where can I get pretrained_nmt_model that matches transformer_s2_iwslt_de_en.

### ISSUE THREAD

**Issue by pdc-kaminaga** [bert-nmt/bert-nmt#21]
Hello,

Sorry to ask such a basic question.
I ran train.ipynb and got "Exception: Cannot load model parameters from checkpoint, please ensure that the architectures match.".
Where can I get pretrained_nmt_model that matches transformer_s2_iwslt_de_en.

I gat model4.pt from
https://github.com/pytorch/fairseq/tree/master/examples/translation
transformer.wmt19.en-de

src = 'en'
tgt = 'de'
bedropout = '0.5'
ARCH = 'transformer_s2_iwslt_de_en'
DATAPATH = 'examples/translation/data_preprocess'
SAVEDIR = 'checkpoints/iwed_' + src + '_' + tgt + '_' + bedropout
your_pretrained_nmt_model = 'wmt19.en-de.joined-dict.ensemble/model4.pt'

!time python train.py $DATAPATH \
-a $ARCH --optimizer adam --lr 0.0005 -s $src -t $tgt --label-smoothing 0.1 \
--dropout 0.3 --max-tokens 4000 --min-lr '1e-09' --lr-scheduler inverse_sqrt --weight-decay 0.0001 \
--criterion label_smoothed_cross_entropy --max-update 150000 --warmup-updates 4000 --warmup-init-lr '1e-07' \
--adam-betas '(0.9,0.98)' --save-dir $SAVEDIR --share-all-embeddings $warmup \
--encoder-bert-dropout --encoder-bert-dropout-ratio $bedropout | tee -a $SAVEDIR/training.log

**Comment by teslacool** [comment]
You should train one model with `transformer_iwslt_de_en` [IWSLT'14 German to English (Transformer)](https://github.com/pytorch/fairseq/tree/master/examples/translation#iwslt14-german-to-english-transformer) rather than `transformer_big`.

**Comment by pdc-kaminaga** [comment]
Thank you for your advice.
I'll try my best!

**Comment by pdc-kaminaga** [comment]
I couldn't find IWSLT'14 German to English (Transformer) Pre-trained model in https://github.com/pytorch/fairseq/tree/master/examples/translation#iwslt14-german-to-english-transformer.
So I did Training a new model/ IWSLT'14 German to English (Transformer) in https://github.com/pytorch/fairseq/tree/master/examples/translation#iwslt14-german-to-english-transformer.
But I got TypeError: make_builder() got an unexpected keyword argument 'vocab_size'.
Please tell me how to solve this problem.

!time bash prepare-iwslt14.sh
!ls -l iwslt14.tokenized.de-en
total 40530
drwx------ 2 root root     4096 Apr 22 06:11 tmp
-rw------- 1 root root    99579 Apr 22 06:12 code
-rw------- 1 root root   806780 Apr 22 06:12 test.de
-rw------- 1 root root   714609 Apr 22 06:12 test.en
-rw------- 1 root root 20170842 Apr 22 06:12 train.de
-rw------- 1 root root 17980010 Apr 22 06:12 train.en
-rw------- 1 root root   910989 Apr 22 06:12 valid.de
-rw------- 1 root root   813577 Apr 22 06:12 valid.en

TEXT = 'iwslt14.tokenized.de-en'
DESTDIR = 'data-bin/iwslt14.tokenized.de-en'
!time fairseq-preprocess --source-lang de --target-lang en \
    --trainpref $TEXT/train --validpref $TEXT/valid --testpref $TEXT/test \
    --destdir $DESTDIR \
    --workers 20

2020-04-22 06:47:42 | INFO | fairseq_cli.preprocess | Namespace(alignfile=None, bert_model_name='bert-base-uncased', cpu=False, criterion='cross_entropy', dataset_impl='cached', destdir='data-bin/iwslt14.tokenized.de-en', fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, joined_dictionary=False, log_format=None, log_interval=1000, lr_scheduler='fixed', memory_efficient_fp16=False, min_loss_scale=0.0001, no_progress_bar=False, nwordssrc=-1, nwordstgt=-1, only_source=False, optimizer='nag', padding_factor=8, seed=1, source_lang='de', srcdict=None, target_lang='en', task='translation', tbmf_wrapper=False, tensorboard_logdir='', testpref='iwslt14.tokenized.de-en/test', tgtdict=None, threshold_loss_scale=None, thresholdsrc=0, thresholdtgt=0, trainpref='iwslt14.tokenized.de-en/train', user_dir=None, validpref='iwslt14.tokenized.de-en/valid', workers=20)
2020-04-22 06:48:02 | INFO | fairseq_cli.preprocess | [de] Dictionary: 8847 types
Traceback (most recent call last):
  File "/usr/local/bin/fairseq-preprocess", line 11, in <module>
    load_entry_point('fairseq', 'console_scripts', 'fairseq-preprocess')()
  File "/content/drive/My Drive/Colab Notebooks/BERT/bert-nmt/fairseq_cli/preprocess.py", line 360, in cli_main
    main(args)
  File "/content/drive/My Drive/Colab Notebooks/BERT/bert-nmt/fairseq_cli/preprocess.py", line 259, in main
    make_all(args.source_lang, src_dict)
  File "/content/drive/My Drive/Colab Notebooks/BERT/bert-nmt/fairseq_cli/preprocess.py", line 241, in make_all
    make_dataset(vocab, args.trainpref, "train", lang, num_workers=args.workers)
  File "/content/drive/My Drive/Colab Notebooks/BERT/bert-nmt/fairseq_cli/preprocess.py", line 237, in make_dataset
    make_binary_dataset(vocab, input_prefix, output_prefix, lang, num_workers)
  File "/content/drive/My Drive/Colab Notebooks/BERT/bert-nmt/fairseq_cli/preprocess.py", line 145, in make_binary_dataset
    impl=args.dataset_impl, vocab_size=len(vocab))
TypeError: make_builder() got an unexpected keyword argument 'vocab_size'

**Comment by teslacool** [comment]
Please confirm that you use our codebase. The location of your error message code is different from our code. Please check it carefully.

**Comment by pdc-kaminaga** [comment]
I'll ask pytorch/fairseq.
Thank you.

**Comment by ijauregiCMCRC** [comment]
I come up with the following error when I try to use a `transformer_iwslt_de_en` as a pretrained NMT model, pretrained with fairseq (0.8.0):

```
RuntimeError: Error(s) in loading state_dict for TransformerS2Model:
	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([4128, 512]) from checkpoint, the shape in current model is torch.Size([8416, 512]).
	size mismatch for decoder.embed_out: copying a param with shape torch.Size([5680, 512]) from checkpoint, the shape in current model is torch.Size([8416, 512]).
	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([5680, 512]) from checkpoint, the shape in current model is torch.Size([8416, 512]).
```
Do I need to use a specific version of fairseq? Do I need to pretrain the NMT model also with your code?

**Comment by teslacool** [comment]
@ijauregiCMCRC The commit version of code we use to train NMT model is a8f28ecb63ee01c33ea9f6986102136743d47ec2.
Your error is because the vocab_size mismatch. You should keep the dict is the same.

**Comment by pdc-kaminaga** [comment]
Hi,
I gat fairseq-generate score = 22.21 and bert-nmt score = 11.12.
Would you please give me some advice to improve the accuracy.

# --------------------
# fairseq-train
# --------------------
!time fairseq-train \
    examples/translation/wmt17_de_en_bin \
    --arch transformer_iwslt_de_en --share-decoder-input-output-embed \
    --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 \
    --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 \
    --dropout 0.3 --weight-decay 0.0001 \
    --criterion label_smoothed_cross_entropy --label-smoothing 0.1 \
    --max-tokens 4096 \
    --eval-bleu \
    --eval-bleu-args '{beam: 5, max_len_a: 1.2, max_len_b: 10}' \
    --eval-bleu-detok moses \
    --eval-bleu-remove-bpe \
    --eval-bleu-print-samples \
    --best-checkpoint-metric bleu --maximize-best-checkpoint-metric

checkpoint_best.pt = checkpoint57.pt
checkpoint_last.pt = checkpoint112.pt

# --------------------
# fairseq-generate
# --------------------
!fairseq-generate examples/translation/wmt17_de_en_bin \
    --path checkpoints/checkpoint_best.pt \
    --batch-size 128 --beam 5 --remove-bpe

2020-04-30 00:05:38 | INFO | fairseq_cli.generate | NOTE: hypothesis and token scores are output in base 2
2020-04-30 00:05:38 | INFO | fairseq_cli.generate | Translated 3003 sentences (78143 tokens) in 22.5s (133.25 sentences/s, 3467.33 tokens/s)
2020-04-30 00:05:38 | INFO | fairseq_cli.generate | Generate test with beam=5: BLEU4 = 22.21, 58.1/29.6/17.2/10.4 (BP=0.943, ratio=0.944, syslen=65096, reflen=68950)

# --------------------
# bert-nmt-train
# --------------------
src = 'de'
tgt = 'en'
bedropout = '0.5'
ARCH = 'transformer_s2_iwslt_de_en'
#DATAPATH = 'examples/translation/data_preprocess_de2en'
DATAPATH = 'examples/translation/wmt17_de_en_bin'
#SAVEDIR = checkpoints/iwed_${src}_${tgt}_${bedropout}
SAVEDIR = 'checkpoints/iwed_' + src + '_' + tgt + '_' + bedropout
your_pretrained_nmt_model = '/content/drive/My\ Drive/Colab\ Notebooks/BERT/BERTによる翻訳/bert-nmt2/checkpoints/checkpoint_best.pt'

!time python train.py $DATAPATH \
-a $ARCH --optimizer adam --lr 0.0005 -s $src -t $tgt --label-smoothing 0.1 \
--dropout 0.3 --max-tokens 4000 --min-lr '1e-09' --lr-scheduler inverse_sqrt --weight-decay 0.0001 \
--criterion label_smoothed_cross_entropy --max-update 150000 --warmup-updates 4000 --warmup-init-lr '1e-07' \
--adam-betas '(0.9,0.98)' --save-dir $SAVEDIR --share-all-embeddings $warmup \
--encoder-bert-dropout --encoder-bert-dropout-ratio $bedropout | tee -a $SAVEDIR/training.log 

checkpoint_best.pt = checkpoint111.pt
checkpoint_last.pt = checkpoint118.pt

# --------------------
# bert-nmt-generate
# --------------------
src = 'de'
tgt = 'en'
bedropout = '0.5'
# ARCH = 'transformer_s2_iwslt_de_en'
DATAPATH = 'examples/translation/wmt17_de_en_bin'
BERT_MODEL_NAME = 'bert-base-uncased'
PATH = 'checkpoints/iwed_de_en_0.5/checkpoint_best.pt'
!time python generate.py  $DATAPATH \
    --bert-model-name $BERT_MODEL_NAME \
    --path $PATH \
    --batch-size 128 --beam 5 --remove-bpe

checkpoint_best.pt = checkpoint78.pt
| Translated 3003 sentences (69734 tokens) in 2007.6s (1.50 sentences/s, 34.74 tokens/s)
| Generate test with beam=5: BLEU4 = 7.53, 37.9/11.7/4.6/1.9 (BP=0.954, ratio=0.955, syslen=65861, reflen=68950)

checkpoint_best.pt = checkpoint82.pt
| Translated 3003 sentences (62818 tokens) in 2172.2s (1.38 sentences/s, 28.92 tokens/s)
| Generate test with beam=5: BLEU4 = 10.12, 45.6/16.8/7.7/3.7 (BP=0.829, ratio=0.842, syslen=58077, reflen=68950)

checkpoint_best.pt = checkpoint97.pt
| Translated 3003 sentences (61146 tokens) in 1739.7s (1.73 sentences/s, 35.15 tokens/s)
| Generate test with beam=5: BLEU4 = 10.69, 47.6/18.2/8.6/4.4 (BP=0.796, ratio=0.814, syslen=56141, reflen=68950)

checkpoint_best.pt = checkpoint111.pt, checkpoint_last.pt =  checkpoint118.pt
| Translated 3003 sentences (63135 tokens) in 2194.4s (1.37 sentences/s, 28.77 tokens/s)
| Generate test with beam=5: BLEU4 = 11.12, 47.3/18.1/8.7/4.4 (BP=0.824, ratio=0.838, syslen=57796, reflen=68950)

**Comment by teslacool** [comment]
Can you check whether your model load BERT model correctly?  I did not see the `--warmup-from-nmt` option in your scripts.

**Comment by pdc-kaminaga** [comment]
Hello,
I'm in the first training
・Set fireseq/checkpoint_best.pt to  bet-mnt/checkpoint_nmt.pt
・Set '--warmup-from-nmt --reset-lr-scheduler' to warmup

!mkdir -p $SAVEDIR

if(os.path.exists(SAVEDIR + '/checkpoint_nmt.pt')):
  print('exist')
else:
  print('Copy it because it does not exist')
  !cp $your_pretrained_nmt_model $SAVEDIR/checkpoint_nmt.pt   <--- First training

!ls -l $SAVEDIR/checkpoint_nmt.pt

if(os.path.exists(SAVEDIR + '/checkpoint_last.pt')):
  print('exist')
  warmup = ''
else:
  print('not exist')
  warmup = '--warmup-from-nmt --reset-lr-scheduler'  <--- First training

# Train
!time python train.py $DATAPATH \
-a $ARCH --optimizer adam --lr 0.0005 -s $src -t $tgt --label-smoothing 0.1 \
--dropout 0.3 --max-tokens 4000 --min-lr '1e-09' --lr-scheduler inverse_sqrt --weight-decay 0.0001 \
--criterion label_smoothed_cross_entropy --max-update 600000 --warmup-updates 4000 --warmup-init-lr '1e-07' \
--adam-betas '(0.9,0.98)' --save-dir $SAVEDIR --share-all-embeddings $warmup \
--encoder-bert-dropout --encoder-bert-dropout-ratio $bedropout | tee -a $SAVEDIR/training.log

**Comment by pdc-kaminaga** [comment]
> Can you check whether your model load BERT model correctly?
I got the following console display for the first bet-nmt-training.

Namespace(activation_dropout=0.0, activation_fn='relu', adam_betas='(0.9,0.98)', adam_eps=1e-08, adaptive_input=False, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, arch='transformer_s2_iwslt_de_en', attention_dropout=0.0, bert_first=True, bert_gates=[1, 1, 1, 1, 1, 1], bert_model_name='bert-base-uncased', bert_output_layer=-1, bert_ratio=1.0, bucket_cap_mb=25, clip_norm=25, cpu=False, criterion='label_smoothed_cross_entropy', curriculum=0, data='examples/translation/wmt17_de_en_bin', dataset_impl='cached', ddp_backend='c10d', decoder_attention_heads=4, decoder_embed_dim=512, decoder_embed_path=None, decoder_ffn_embed_dim=1024, decoder_input_dim=512, decoder_layers=6, decoder_learned_pos=False, decoder_no_bert=False, decoder_normalize_before=False, decoder_output_dim=512, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.3, encoder_attention_heads=4, encoder_bert_dropout=True, encoder_bert_dropout_ratio=0.5, encoder_bert_mixup=False, encoder_embed_dim=512, encoder_embed_path=None, encoder_ffn_embed_dim=1024, encoder_layers=6, encoder_learned_pos=False, encoder_normalize_before=False, encoder_ratio=1.0, find_unused_parameters=False, finetune_bert=False, fix_batches_to_gpus=False, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, keep_interval_updates=-1, keep_last_epochs=-1, label_smoothing=0.1, lazy_load=False, left_pad_source='True', left_pad_target='False', log_format=None, log_interval=1000, lr=[0.0005], lr_scheduler='inverse_sqrt', mask_cls_sep=False, max_epoch=0, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=4000, max_update=600000, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=1e-09, no_epoch_checkpoints=False, no_progress_bar=False, no_save=False, no_token_positional_embeddings=False, num_workers=0, optimizer='adam', optimizer_overrides='{}', raw_text=False, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=True, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='checkpoints/iwed_de_en_0.5', save_interval=1, save_interval_updates=0, seed=1, sentence_avg=False, share_all_embeddings=True, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang='de', target_lang='en', task='translation', tbmf_wrapper=False, tensorboard_logdir='', threshold_loss_scale=None, train_subset='train', update_freq=[1], upsample_primary=1, user_dir=None, valid_subset='valid', validate_interval=1, warmup_from_nmt=True, warmup_init_lr=1e-07, warmup_nmt_file='checkpoint_nmt.pt', warmup_updates=4000, weight_decay=0.0001)
| [de] dictionary: 39808 types
| [en] dictionary: 39808 types
| examples/translation/wmt17_de_en_bin valid de-en 2605 examples
bert_gates [True, True, True, True, True, True]
TransformerS2Model(
  (encoder): TransformerS2Encoder(
    (embed_tokens): Embedding(39808, 512, padding_idx=1)
    (embed_positions): SinusoidalPositionalEmbedding()
    (layers): ModuleList(
      (0): TransformerS2EncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (bert_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm(torch.Size([512]), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=1024, bias=True)
        (fc2): Linear(in_features=1024, out_features=512, bias=True)
        (final_layer_norm): LayerNorm(torch.Size([512]), eps=1e-05, elementwise_affine=True)
      )
      (1): TransformerS2EncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (bert_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm(torch.Size([512]), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=1024, bias=True)
        (fc2): Linear(in_features=1024, out_features=512, bias=True)
        (final_layer_norm): LayerNorm(torch.Size([512]), eps=1e-05, elementwise_affine=True)
      )
      ・
      ・
      ・
      )
    )
  )
  (decoder): TransformerDecoder(
    (embed_tokens): Embedding(39808, 512, padding_idx=1)
    (embed_positions): SinusoidalPositionalEmbedding()
    (layers): ModuleList(
      (0): TransformerDecoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (self_attn_layer_norm): LayerNorm(torch.Size([512]), eps=1e-05, elementwise_affine=True)
        (encoder_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (bert_attn): MultiheadAttention(
          (out_proj): Linear(in_features=512, out_features=512, bias=True)
        )
        (encoder_attn_layer_norm): LayerNorm(torch.Size([512]), eps=1e-05, elementwise_affine=True)
        (fc1): Linear(in_features=512, out_features=1024, bias=True)
        (fc2): Linear(in_features=1024, out_features=512, bias=True)
        (final_layer_norm): LayerNorm(torch.Size([512]), eps=1e-05, elementwise_affine=True)
      )
      ・
      ・
      ・
    )
  )
  (bert_encoder): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): BertLayerNorm()
      (dropout): Dropout(p=0.1)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): BertLayerNorm()
              (dropout): Dropout(p=0.1)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): BertLayerNorm()
            (dropout): Dropout(p=0.1)
          )
        )
      ・
      ・
      ・
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
| epoch 057:   3% 179/5264 [00:59<27:37,  3.07it/s, loss=11.141, nll_loss=10.461, ppl=1409.63, wps=2328, ups=2, wpb=1422.704, bsz=49.341, num_updates=179, lr=2.24705e-05, gnorm=7.909, clip=0.011, oom=0.000, wall=109, train_wall=57]

**Comment by yataixx** [comment]
> I come up with the following error when I try to use a `transformer_iwslt_de_en` as a pretrained NMT model, pretrained with fairseq (0.8.0):
> 
> ```
> RuntimeError: Error(s) in loading state_dict for TransformerS2Model:
> 	size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([4128, 512]) from checkpoint, the shape in current model is torch.Size([8416, 512]).
> 	size mismatch for decoder.embed_out: copying a param with shape torch.Size([5680, 512]) from checkpoint, the shape in current model is torch.Size([8416, 512]).
> 	size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([5680, 512]) from checkpoint, the shape in current model is torch.Size([8416, 512]).
> ```
> 
> Do I need to use a specific version of fairseq? Do I need to pretrain the NMT model also with your code?

Do you solve the size mismatch problem? could you tell me the solution. Thank you

**Comment by ecoli-hit** [comment]
> Hi, I gat fairseq-generate score = 22.21 and bert-nmt score = 11.12. Would you please give me some advice to improve the accuracy.
> 
> # --------------------
> # fairseq-train
> # --------------------
> !time fairseq-train examples/translation/wmt17_de_en_bin --arch transformer_iwslt_de_en --share-decoder-input-output-embed --optimizer adam --adam-betas '(0.9, 0.98)' --clip-norm 0.0 --lr 5e-4 --lr-scheduler inverse_sqrt --warmup-updates 4000 --dropout 0.3 --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --label-smoothing 0.1 --max-tokens 4096 --eval-bleu --eval-bleu-args '{beam: 5, max_len_a: 1.2, max_len_b: 10}' --eval-bleu-detok moses --eval-bleu-remove-bpe --eval-bleu-print-samples --best-checkpoint-metric bleu --maximize-best-checkpoint-metric
> 
> checkpoint_best.pt = checkpoint57.pt checkpoint_last.pt = checkpoint112.pt
> 
> # --------------------
> # fairseq-generate
> # --------------------
> !fairseq-generate examples/translation/wmt17_de_en_bin --path checkpoints/checkpoint_best.pt --batch-size 128 --beam 5 --remove-bpe
> 
> 2020-04-30 00:05:38 | INFO | fairseq_cli.generate | NOTE: hypothesis and token scores are output in base 2 2020-04-30 00:05:38 | INFO | fairseq_cli.generate | Translated 3003 sentences (78143 tokens) in 22.5s (133.25 sentences/s, 3467.33 tokens/s) 2020-04-30 00:05:38 | INFO | fairseq_cli.generate | Generate test with beam=5: BLEU4 = 22.21, 58.1/29.6/17.2/10.4 (BP=0.943, ratio=0.944, syslen=65096, reflen=68950)
> 
> # --------------------
> # bert-nmt-train
> # --------------------
> src = 'de' tgt = 'en' bedropout = '0.5' ARCH = 'transformer_s2_iwslt_de_en' #DATAPATH = 'examples/translation/data_preprocess_de2en' DATAPATH = 'examples/translation/wmt17_de_en_bin' #SAVEDIR = checkpoints/iwed_${src}_${tgt}_${bedropout} SAVEDIR = 'checkpoints/iwed_' + src + '_' + tgt + '_' + bedropout your_pretrained_nmt_model = '/content/drive/My\ Drive/Colab\ Notebooks/BERT/BERTによる翻訳/bert-nmt2/checkpoints/checkpoint_best.pt'
> 
> !time python train.py $DATAPATH -a $ARCH --optimizer adam --lr 0.0005 -s $src -t $tgt --label-smoothing 0.1 --dropout 0.3 --max-tokens 4000 --min-lr '1e-09' --lr-scheduler inverse_sqrt --weight-decay 0.0001 --criterion label_smoothed_cross_entropy --max-update 150000 --warmup-updates 4000 --warmup-init-lr '1e-07' --adam-betas '(0.9,0.98)' --save-dir $SAVEDIR --share-all-embeddings $warmup --encoder-bert-dropout --encoder-bert-dropout-ratio $bedropout | tee -a $SAVEDIR/training.log
> 
> checkpoint_best.pt = checkpoint111.pt checkpoint_last.pt = checkpoint118.pt
> 
> # --------------------
> # bert-nmt-generate
> # --------------------
> src = 'de' tgt = 'en' bedropout = '0.5'
> 
> # ARCH = 'transformer_s2_iwslt_de_en'
> DATAPATH = 'examples/translation/wmt17_de_en_bin' BERT_MODEL_NAME = 'bert-base-uncased' PATH = 'checkpoints/iwed_de_en_0.5/checkpoint_best.pt' !time python generate.py $DATAPATH --bert-model-name $BERT_MODEL_NAME --path $PATH --batch-size 128 --beam 5 --remove-bpe
> 
> checkpoint_best.pt = checkpoint78.pt | Translated 3003 sentences (69734 tokens) in 2007.6s (1.50 sentences/s, 34.74 tokens/s) | Generate test with beam=5: BLEU4 = 7.53, 37.9/11.7/4.6/1.9 (BP=0.954, ratio=0.955, syslen=65861, reflen=68950)
> 
> checkpoint_best.pt = checkpoint82.pt | Translated 3003 sentences (62818 tokens) in 2172.2s (1.38 sentences/s, 28.92 tokens/s) | Generate test with beam=5: BLEU4 = 10.12, 45.6/16.8/7.7/3.7 (BP=0.829, ratio=0.842, syslen=58077, reflen=68950)
> 
> checkpoint_best.pt = checkpoint97.pt | Translated 3003 sentences (61146 tokens) in 1739.7s (1.73 sentences/s, 35.15 tokens/s) | Generate test with beam=5: BLEU4 = 10.69, 47.6/18.2/8.6/4.4 (BP=0.796, ratio=0.814, syslen=56141, reflen=68950)
> 
> checkpoint_best.pt = checkpoint111.pt, checkpoint_last.pt = checkpoint118.pt | Translated 3003 sentences (63135 tokens) in 2194.4s (1.37 sentences/s, 28.77 tokens/s) | Generate test with beam=5: BLEU4 = 11.12, 47.3/18.1/8.7/4.4 (BP=0.824, ratio=0.838, syslen=57796, reflen=68950)

Hi i been used the same way to train a pretrained model with fairseq which version is a8f28ecb63ee01c33ea9f6986102136743d47ec2
but when i use the training script as you post in your guidence there are some errors
1. ARCH = transformer_s2_iwslt_de_en
![image](https://user-images.githubusercontent.com/74221501/185754177-2bba4bd9-9f42-43f8-9845-e75510cb3ccd.png)
2. ARCH = transformer_iwslt_de_en
![image](https://user-images.githubusercontent.com/74221501/185754200-e86cf6d3-73c0-4f64-b536-fbf7fe5f9529.png)
could you please help me solve this problem? @teslacool 
this is my environment 
![image](https://user-images.githubusercontent.com/74221501/185754279-4e6259e2-5050-4719-b3ae-81cf225aa9d4.png)
I trained the pretrained model with https://github.com/facebookresearch/fairseq/tree/main/examples/translation#iwslt14-german-to-english-transformer

**Comment by pdc-dev** [comment]
I've confirmed that my environment doesn't work either.
I'll try reprocessing with the latest instructions given in the README.md.
I am sorry that I can not be a help.
