### ISSUE TITLE
Interactive evaluation script

### ISSUE THREAD

**Issue by LividWo** [bert-nmt/bert-nmt#24]
Neat work. Congratulation.

In the paper, you mentioned that you are using multi-bleu.perl to evaluate IWSLT’14 En↔De, but in the script provided ("iwslt-interactive.sh"), you are evaluating with sacrebleu. 

I tried myself, but somehow generate.py outperform interactive.py for about 1 bleu point. I guess the gap comes from the tokenization problem?

Would you mind updating the evaluation script for iwslt14?

**Comment by teslacool** [comment]
For Iwslt14 EnDe, we just use  `generate.py` for evaluation, this `iwslt-interactive.sh` is for other Iwslt tasks.

**Comment by LividWo** [comment]
question well addressed.
