### ISSUE TITLE
--encoder-bert-dropout-ratio meaning?

### ISSUE THREAD

**Issue by mirzakhalov** [bert-nmt/bert-nmt#29]
The paper mentions the range of [0, 1.0] for drop net probability, but the code uses [0, 0.5]. Any difference between them? And what happens when ratio is lower like 0.1 or 0.0?

**Comment by teslacool** [comment]
The `--encoder-bert-dropout-ratio` in code corresponds to `p_net/2`  in paper. Sorry for the inconsistency here, but it has no effect on the final result.

The lower ratio may easily lead to overfitting as stated in our paper.

**Comment by mirzakhalov** [comment]
Thank you!

**Comment by mirzakhalov** [comment]
Any comments/explanation on these parameters?

```
--encoder-bert-mixup
--decoder-no-bert
```

**Comment by teslacool** [comment]
`--encoder-bert-mixup`  is another attempt to reduce overfitting, whose effect is not as good as dropout. You can see the [code](https://github.com/bert-nmt/bert-nmt/blob/cd79c1d3cd387652a407d3ecf0a4a4fda92b95a0/fairseq/models/transformer.py#L1373) for more details.

`--decoder-no-bert` is one option for our ablation experiments to study the encoder-bert-attn and decoder-bert-attn separately.
