### ISSUE TITLE
How to train bert fused NMT model using my own BERT model

### ISSUE THREAD

**Issue by Binteislam** [bert-nmt/bert-nmt#30]
I want to train bert fused NMT using my own BERT model, kindly guide me the proper process to do that.

**Comment by teslacool** [comment]
You just add this model and tokenizer in [bert](https://github.com/bert-nmt/bert-nmt/tree/master/bert), and the remaining steps are the same.

**Comment by Binteislam** [comment]
Much thanks for your response, I'll try this and report back soon!

**Comment by cherryas** [comment]
hello, could you please provide more details? I have tried to preprocess data with "--bert-model-name my/own/bert/path", but it failed without vocab.txt.

**Comment by teslacool** [comment]
Yes, it need one model checkpoint to load model weight and one vocab file to act as dictionary when splitting words.

You can debug the example in README to figure this out.

**Comment by cherryas** [comment]
> Yes, it need one model checkpoint to load model weight and one vocab file to act as dictionary when splitting words.
> 
> You can debug the example in README to figure this out.

ok, thank you very much!
