### ISSUE TITLE
Cannot resume training

### ISSUE THREAD

**Issue by mrqorib** [bert-nmt/bert-nmt#31]
Hi, thank you for your work.

I encounter a problem when resuming my training, somehow the training will restart from the first epoch again. The log is as below
```
| model transformer_s2_vaswani_wmt_en_de_big, criterion LabelSmoothedCrossEntropyCriterion
| num. model params: 354184960 (num. trained: 245874688)
| training on 1 GPUs
| max tokens per GPU = 3050 and max sentences per GPU = None
Model will load checkpoint from ../model/bert-base-cased/2222/checkpoint_last.pt
| loaded checkpoint ../model/bert-base-cased/2222/checkpoint_last.pt (epoch 8 @ 0 updates)
| loading train data for epoch 0
| ../process/bin train src-trg 1159547 examples
| saved checkpoint ../model/bert-base-cased/2222/checkpoint0.pt (epoch 0 @ 0 updates) (writing took 530.7144210338593 seconds)
```
Even though I have trained it for 8 epochs it is restarting from the first epoch. Do you have any idea how this happens? Thank you very much.

Warm regards,
Reza Qorib

**Comment by teslacool** [comment]
From your log, `loaded checkpoint ../model/bert-base-cased/2222/checkpoint_last.pt (epoch 8 @ 0 updates)`, it seemed that your job did resume from checkpoint_8.pt (it is the same as checkpoint_last.pt).

You should paste your scripts used to run this job and the entire log, and I will do a better check.
