### ISSUE TITLE
Way to visualize/observe the way BERT Attention being used in training and inference?

### ISSUE THREAD

**Issue by mirzakhalov** [bert-nmt/bert-nmt#32]
Is there any way I can check the extent by which BERT Attention is being used both in the encoder and decoder level? Is there anything in the code that can help me do this? Basically, I would want to see if BERT Attention is being used and if it is different at inference time vs training time

**Comment by teslacool** [comment]
You may need the attn_weight in [multihead-attn](https://github.com/bert-nmt/bert-nmt/blob/cd79c1d3cd387652a407d3ecf0a4a4fda92b95a0/fairseq/modules/multihead_attention.py#L230).

**Comment by mirzakhalov** [comment]
Thanks! But how to differentiate BERT Attention form Encoder/Decoder attention since it just seems to be defined as attention there?

**Comment by teslacool** [comment]
You can return these two different attn_weighs to different dicts (you need to modify some code).
