### ISSUE TITLE
Bugs? when finetune BERT

### ISSUE THREAD

**Issue by LividWo** [bert-nmt/bert-nmt#34]
when we want to finetune BERT during translation, we turn on --finetune_bert.
However, I noticed that in train.py L54-56, you disable the update of BERT's pooler, can you explain a bit why you turn off the update of the pooling layer?

**Comment by teslacool** [comment]
We will not use pooling layer. Exactly, we use the last block output of BERT.
 
I disable the update there, so these parameter will not included by optimizer. Pytorch multi-gpu training will fail if you include some parameters without grad (pytorch 1.0).

**Comment by LividWo** [comment]
> We will not use pooling layer. Exactly, we use the last block output of BERT.
> 
> I disable the update there, so these parameter will not included by optimizer. Pytorch multi-gpu training will fail if you include some parameters without grad (pytorch 1.0).

I see. Thanks for your quick reply.
