### ISSUE TITLE
Question regarding datapath

### ISSUE THREAD

**Issue by seanggggggg** [bert-nmt/bert-nmt#35]
Hello, I am currently trying to use your code for nmt task. While working on the demo one using fairseq/examples/translation/prepare-iwslt14.sh and following your instruction on datapreprocessing. 

After that, I tried to train the bert-fused NMT model, however, I encountered below error. I am not sure where does it come about, does it have something to do with my data path? 

for data path, I have put all of the bert-preprocessed files using your code "preprocess.py" to this path: /content/bert-nmt/bert-nmt-files/Bert-NMT-files

I would sincerely appreciate if you could take a look at these following error message and give me some ideas on where to modify them. Thank you!

Traceback (most recent call last):
Namespace(activation_dropout=0.0, activation_fn='relu', adam_betas='(0.9,0.98)', adam_eps=1e-08, adaptive_input=False, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, arch='transformer_s2_iwslt_de_en', attention_dropout=0.0, bert_first=True, bert_gates=[1, 1, 1, 1, 1, 1], bert_model_name='bert-base-uncased', bert_output_layer=-1, bert_ratio=1.0, bucket_cap_mb=25, clip_norm=25, cpu=False, criterion='label_smoothed_cross_entropy', curriculum=0, data='/content/bert-nmt/bert-nmt-files/Bert-NMT-files', dataset_impl='cached', ddp_backend='c10d', decoder_attention_heads=4, decoder_embed_dim=512, decoder_embed_path=None, decoder_ffn_embed_dim=1024, decoder_input_dim=512, decoder_layers=6, decoder_learned_pos=False, decoder_no_bert=False, decoder_normalize_before=False, decoder_output_dim=512, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_port=-1, distributed_rank=0, distributed_world_size=1, dropout=0.3, encoder_attention_heads=4, encoder_bert_dropout=True, encoder_bert_dropout_ratio=0.5, encoder_bert_mixup=False, encoder_embed_dim=512, encoder_embed_path=None, encoder_ffn_embed_dim=1024, encoder_layers=6, encoder_learned_pos=False, encoder_normalize_before=False, encoder_ratio=1.0, find_unused_parameters=False, finetune_bert=False, fix_batches_to_gpus=False, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, keep_interval_updates=-1, keep_last_epochs=-1, label_smoothing=0.1, lazy_load=False, left_pad_source='True', left_pad_target='False', log_format=None, log_interval=1000, lr=[0.0005], lr_scheduler='inverse_sqrt', mask_cls_sep=False, max_epoch=0, max_sentences=None, max_sentences_valid=None, max_source_positions=1024, max_target_positions=1024, max_tokens=4000, max_update=150000, memory_efficient_fp16=False, min_loss_scale=0.0001, min_lr=1e-09, no_epoch_checkpoints=False, no_progress_bar=False, no_save=False, no_token_positional_embeddings=False, num_workers=0, optimizer='adam', optimizer_overrides='{}', raw_text=False, required_batch_size_multiple=8, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', save_dir='checkpoints/iwed_${src}_${tgt}_${bedropout}', save_interval=1, save_interval_updates=0, seed=1, sentence_avg=False, share_all_embeddings=True, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang='en', target_lang='de', task='translation', tbmf_wrapper=False, tensorboard_logdir='', threshold_loss_scale=None, train_subset='train', update_freq=[1], upsample_primary=1, user_dir=None, valid_subset='valid', validate_interval=1, warmup_from_nmt=False, warmup_init_lr=1e-07, warmup_nmt_file='checkpoint_nmt.pt', warmup_updates=4000, weight_decay=0.0001)
| [en] dictionary: 10152 types
| [de] dictionary: 10152 types
| /content/bert-nmt/bert-nmt-files/Bert-NMT-files valid en-de 7283 examples
  File "/content/bert-nmt/train.py", line 315, in <module>
    cli_main()
  File "/content/bert-nmt/train.py", line 311, in cli_main
    main(args)
  File "/content/bert-nmt/train.py", line 46, in main
    task.load_dataset(valid_sub_split, combine=True, epoch=0)
  File "/content/bert-nmt/fairseq/tasks/translation.py", line 213, in load_dataset
    bert_model_name = self.bert_model_name
  File "/content/bert-nmt/fairseq/tasks/translation.py", line 80, in load_langpair_dataset
    srcbert_datasets, srcbert_datasets.sizes, berttokenizer,
AttributeError: 'NoneType' object has no attribute 'sizes'

**Comment by seanggggggg** [comment]
I also tried to downgrade PyTorch to 1.1.0, but the error still exists

**Comment by teslacool** [comment]
Did you use [makedataforbert.sh](https://github.com/bert-nmt/bert-nmt/blob/master/examples/translation/makedataforbert.sh) to prepare data for BERT input?

**Comment by seanggggggg** [comment]
> Did you use [makedataforbert.sh](https://github.com/bert-nmt/bert-nmt/blob/master/examples/translation/makedataforbert.sh) to prepare data for BERT input?

Thank you for your reply. Yes, I did. I used these following codes, and moved the files in the path to /content/bert-nmt/bert-nmt-files/Bert-NMT-files.

Here is the code I used:

!bash '/content/drive/My Drive/Colab Notebooks/makedataforbert_en.sh'

!bash '/content/drive/My Drive/Colab Notebooks/makedataforbert_de.sh'

!python /content/bert-nmt/preprocess.py --source-lang de --target-lang en \
  --trainpref /content/iwslt14.tokenized.de-en/train --validpref /content/iwslt14.tokenized.de-en/valid --testpref /content/iwslt14.tokenized.de-en/test \
  --destdir '/content/drive/My Drive/Colab Notebooks/Bert-NMT-files'  --joined-dictionary --bert-model-name bert-base-uncased

**Comment by teslacool** [comment]
Please see [line](https://github.com/bert-nmt/bert-nmt/blob/cd79c1d3cd387652a407d3ecf0a4a4fda92b95a0/fairseq/data/indexed_dataset.py#L36), and I guess that `IndexedDataset.exists(path)==False`.  So can you check whether this file exists?

**Comment by seanggggggg** [comment]
> Please see [line](https://github.com/bert-nmt/bert-nmt/blob/cd79c1d3cd387652a407d3ecf0a4a4fda92b95a0/fairseq/data/indexed_dataset.py#L36), and I guess that `IndexedDataset.exists(path)==False`. So can you check whether this file exists?

Thank you for your reply. For the path here, I used the path where I stored the preprocessed bert input (files such as dict.de, dict.en, test.bert.de-en.de.bin etc). Am I misunderstanding it here?

PS: The code correctly outputs the message:" /content/bert-nmt/Bert-NMT-files valid en-de 7283 examples "

**Comment by seanggggggg** [comment]
> > Please see [line](https://github.com/bert-nmt/bert-nmt/blob/cd79c1d3cd387652a407d3ecf0a4a4fda92b95a0/fairseq/data/indexed_dataset.py#L36), and I guess that `IndexedDataset.exists(path)==False`. So can you check whether this file exists?
> 
> Thank you for your reply. For the path here, I used the path where I stored the preprocessed bert input (files such as dict.de, dict.en, test.bert.de-en.de.bin etc). Am I misunderstanding it here?
> 
> PS: The code correctly outputs the message:" /content/bert-nmt/Bert-NMT-files valid en-de 7283 examples "

I realized that in the data path, there is no file named as valid.bert.de-en.en etc. I am wondering for the data_path here, which path are we supposed to use. So we are not supposed to use the path where we stored the preprocessed files?

**Comment by teslacool** [comment]
I carefully checked  your log, and found that you build data (src=de tgt=en), but you train nmt model with different direction (src=en, tgt=de). So your binarized data do not exist.

**Comment by seanggggggg** [comment]
> I carefully checked your log, and found that you build data (src=de tgt=en), but you train nmt model with different direction (src=en, tgt=de). So your binarized data do not exist.

Thank you much again, i also realized that I accidentally put de and en in opposite places. In the meantime, I would like to know if it is required for us to have a pre-trained nmt model using fairseq (checkpoint_last.pt)?

**Comment by teslacool** [comment]
Yes, you should pretrain an nmt model using fairseq (better use the same version).

**Comment by seanggggggg** [comment]
> Yes, you should pretrain an nmt model using fairseq (better use the same version).

Thank you very much!
