### ISSUE TITLE
Using our own data for nmt task with bert-nmt

### ISSUE THREAD

**Issue by seanggggggg** [bert-nmt/bert-nmt#36]
Hello, I would like to know if there is a way to change the dataset for nmt task. I am trying to use bert-nmt on my own dataset (English to English, description generation) and would like to know if there would be a better way for me to use my own dataset, rather than use code like below (others' dataset):

!bash fairseq/examples/translation/prepare-iwslt14.sh

I am currently trying to change the files from the folder created from the above dataset, but is it the correct way for me to do so, would there be other alternative way to change the dataset (mine is a csv file) and still use bert-nmt to conduct the task?

**Comment by teslacool** [comment]
Sorry for the late reply.

I am not familiar with the description generation task.
But I think the input is totally the same as that in vanilla Transformer, except that you should prepare an input for bert  (sentences without any preprocessing).
