### ISSUE TITLE
Running Preliminary Explorations

### ISSUE THREAD

**Issue by oshaikh13** [bert-nmt/bert-nmt#37]
Hey there -- wanted to start by saying thanks for the excellent work!

I'm trying to run some of the preliminary experiments, but I'm not sure how I'd go about doing the following:

(1): Initializing the Encoder with BERT: The ```transformer_iwslt_de_en``` architecture has only 6 encoder layers, but BERT-base has 12 decoder layers. I'm not sure what layers were selected to initialize the NMT encoder. I think I see code for doing this with XLM (https://github.com/bert-nmt/bert-nmt/blob/master/fairseq/models/transformer_from_pretrained_xlm.py), but not with BERT.

(2): I'm also not sure if there's code for running this case: "Leveraging the output of BERT as embedding;" if you could point me in the right direction, I'd really appreciate it.

Thanks a ton!
Omar

edit: My guess is this has something to do with bert_gates and bert_ratio/encoder_ratio, but I'm not entirely sure.

**Comment by teslacool** [comment]
Sorry for the late reply.

Some preliminary experiments are conducted on different git branch, and thus they may not be included in this repo.

(1)initializing the encoder with bert: we just replace the encoder with the bert model (so the encoder is 12-layers).
(2)"Leveraging the output of BERT as embedding;": it is on one different branch. If you are interested in this part, you can contact me by email.
