### ISSUE TITLE
Get error when I ensemble models 

### ISSUE THREAD

**Issue by linhaow** [bert-nmt/bert-nmt#38]
decode_one_ () miss 1 argument

**Comment by teslacool** [comment]
Sorry for my late reply.

We do the ensemble work at paper rebuttal stage, and did not push those commits to this repo.

If you need to do ensemble, please replace `sequence_generator.py` file with the [sequence_generator_ensemble.py](https://github.com/bert-nmt/bert-nmt/blob/master/fairseq/sequence_generator_ensemble.py) file.
