### ISSUE TITLE
Could you please point out the key code? there are too many fairseq code

### ISSUE THREAD

**Issue by guotong1988** [bert-nmt/bert-nmt#40]
thank you very much

**Comment by teslacool** [comment]
@guotong1988 The most important part is to understand our  architecture. You can read the [fairseq/models/transformer.py](https://github.com/bert-nmt/bert-nmt/blob/0e4c37abc1fb377ddaa4b060a7492b51ee92c8d0/fairseq/models/transformer.py#L175) file for more details.
