### ISSUE TITLE
Can I trained Bert-fuse model with my pretrained-Roberta

### ISSUE THREAD

**Issue by HieuNgoUIT** [bert-nmt/bert-nmt#41]
Hi, I've been trying to customize the code lately but it can't work because in my language there is only a pre-trained Roberta model.  Can I have insight on how to do that? Thank you

**Comment by tranhamduong** [comment]
sharing the same problem with @HieuNgoUIT

**Comment by teslacool** [comment]
We will update the code to support more pretrained models included in [huggingface/transformers](https://github.com/huggingface/transformers)  in the coming days.

**Comment by teslacool** [comment]
@HieuNgoUIT @tranhamduong We have updated our code.

**Comment by tranhamduong** [comment]
Wow, many thanks to you, I am highly appreciate your effort!
