### ISSUE TITLE
How  to train a model without bert by your code?

### ISSUE THREAD

**Issue by Sry2016** [bert-nmt/bert-nmt#42]
I use your framwork to train a transformer model by fairseq-train, then print the model arch, but i see there is a bert.
Any influence ?

**Comment by teslacool** [comment]
You should train a model without bert using standard [fairseq](https://github.com/pytorch/fairseq) repo. The commit version is `a8f28ecb63ee01c33ea9f6986102136743d47ec2`.

**Comment by Sry2016** [comment]
Thank you. You mean that I firstly train a transformer model by standard fairseq, then I move the checkpoint_best.pt to your framework? Then I can train bertnmt with a pretrained model ?

**Comment by teslacool** [comment]
Yes. @Sry2016

**Comment by Sry2016** [comment]
Sorry to disturb you again. How to install the same version fairseq with you?  What's this mean "a8f28ecb63ee01c33ea9f6986102136743d47ec2" ?

**Comment by teslacool** [comment]
git checkout a8f28ecb63ee01c33ea9f6986102136743d47ec2
