### ISSUE TITLE
How to use interactive.py

### ISSUE THREAD

**Issue by Sry2016** [bert-nmt/bert-nmt#43]
Can you provide some examples?
what's the bpefile?
 
sed -r 's/(@@ )|(@@ ?$)//g' $bpefile > $bpefile.debpe
$MOSE/scripts/tokenizer/detokenizer.perl -l $src < $bpefile.debpe > $bpefile.debpe.detok
paste -d "\n" $bpefile $bpefile.debpe.detok > $bpefile.in
cat $bpefile.in | python interactive.py  -s $src -t $tgt \
--buffer-size 1024 --batch-size 128 --beam 5 --remove-bpe  > output.log

**Comment by Sry2016** [comment]
Is it a raw source dataset needs to be translated or a preprocessed file ?

**Comment by teslacool** [comment]
It is a preprocessed file after tokenization and bpe like those used by preprocess.py.
