### ISSUE TITLE
Error in pre-processing module with update-20-10 branch

### ISSUE THREAD

**Issue by jalajthanaki** [bert-nmt/bert-nmt#48]
Hi Team,

I really appreciate your research work. I started trying out your code base. I'm using code base from _**update-20-10**_ branch. When my training script reach to the preprocessing stage. I'm getting following error trace. Can you please help me resolve this? Have I missed on something?

```Traceback (most recent call last):
  File "bert-nmt/preprocess.py", line 274, in <module>
    cli_main()
  File "bert-nmt/preprocess.py", line 270, in cli_main
    main(args)
  File "bert-nmt/preprocess.py", line 191, in main
    make_all(args.source_lang, berttokenizer)
  File "bert-nmt/preprocess.py", line 176, in make_all
    make_dataset(vocab, args.trainpref, "train", lang, num_workers=args.workers)
  File "bert-nmt/preprocess.py", line 172, in make_dataset
    make_binary_dataset(vocab, input_prefix, output_prefix, lang, num_workers)
  File "bert-nmt/preprocess.py", line 138, in make_binary_dataset
    offset=0, end=offsets[1]
  File "bert-nmt/fairseq/binarizer.py", line 60, in binarize
    ids = dict.encode_line(
AttributeError: 'BertTokenizerFast' object has no attribute 'encode_line'
```
I have install the dependencies using[ this docker files](https://github.com/bert-nmt/bert-nmt/blob/update-20-10/Dockerfile).

Thanks,

**Comment by teslacool** [comment]
@jalajthanaki Which BERT model do you use?

**Comment by jalajthanaki** [comment]
Hi @teslacool, Thanks for getting back on this thread. I'm using  **bert-base-cased** model. I'm using transformers==4.0.1. Is there anything that I'm missing?

**Comment by teslacool** [comment]
Can you try it with `transformers==3.5.0`?

**Comment by jalajthanaki** [comment]
> Can you try it with `transformers==3.5.0`?

Yes I will try and post my findings here. Thank you again for the help.
