### ISSUE TITLE
What are the development sets and test sets in the direction of IWSLT 2017 en-zh?

### ISSUE THREAD

**Issue by IdaBetsy** [bert-nmt/bert-nmt#49]
Hello, is the development set you use in the direction of IWSLT en-zh IWSLT2016? Is the test set IWSLT 2017?
If it is convenient, can you provide the pre-processing script before bpe? If you are using the prepare-iwslt14.sh script on fairseq, there is an echo "creating train, valid, test ... "step in the preprocessing. I don't know why. Do you need this when doing en-zh？
<img width="663" alt="C75D688E-2BA5-4043-BA0B-905EA6BC7337" src="https://user-images.githubusercontent.com/58454588/102678015-7bc63880-41e0-11eb-90b7-02b39a621270.png">

Thank you very much and look forward to your reply.
@teslacool

**Comment by teslacool** [comment]
Please refer to this [file](https://github.com/teslacool/preprocess_iwslt/blob/master/preprocess.sh).

**Comment by IdaBetsy** [comment]
Thank you very much for your reply. When I ran this script, I got an error that I couldn't find the page. What is the correct page for downloading corpus?
![IMG_4144](https://user-images.githubusercontent.com/58454588/102682845-8f38ca00-4207-11eb-8664-07890e118f58.JPG)

**Comment by IdaBetsy** [comment]
Thank you very much for your reply. When I ran this script, I got an error that I couldn't find the page. What is the correct page for downloading corpus?
![IMG_4144](https://user-images.githubusercontent.com/58454588/102682901-e8a0f900-4207-11eb-8e15-87045d07d535.JPG)
Thank you very much and look forward to your reply.
@teslacool

**Comment by teslacool** [comment]
Sorry, the website is currently under maintenance. See more details from [official website](https://wit3.fbk.eu/home).

> The site is currently under maintenance. If you need some data listed below whose link is not working yet, please contact Mauro Cettolo (cettolo AT fbk DOT eu). Sorry for any inconvenience.

**Comment by IdaBetsy** [comment]
> Sorry, the website is currently under maintenance. See more details from [official website](https://wit3.fbk.eu/home).
> 
> > The site is currently under maintenance. If you need some data listed below whose link is not working yet, please contact Mauro Cettolo (cettolo AT fbk DOT eu). Sorry for any inconvenience.

Ok, thank you very much for your reply.
