### ISSUE TITLE
Problems using Interactive.py

### ISSUE THREAD

**Issue by echan00** [bert-nmt/bert-nmt#5]
I am following the instructions in the readme regarding using interactive.py:

```
sed -r 's/(@@ )|(@@ ?$)//g' $bpefile > $bpefile.debpe
$MOSE/scripts/tokenizer/detokenizer.perl -l $src < $bpefile.debpe > $bpefile.debpe.detok
paste -d "\n" $bpefile $bpefile.debpe.detok > $bpefile.in
cat $bpefile.in | python interactive.py  -s $src -t $tgt \
--buffer-size 1024 --batch-size 128 --beam 5 --remove-bpe  > output.log
```

Is $bpefile a file containing the source sentences after bpe has been applied to it? (e.g test.en?)

Also, the following execution gives an error as the 'data' argument is missing:
`cat $bpefile.in | python interactive.py  -s $src -t $tgt --buffer-size 1024 --batch-size 128 --beam 5 --remove-bpe  > output.log`

**Comment by bert-nmt** [comment]
Yes, the $bpefile is a file containing source sentences after bpe operation, and we need to do debpe and detokenization to get input sentences for Bert (and you may have another way to get this input ).

In interactive mode, the data is read from stdin (cat $bpefile.in ).

**Comment by echan00** [comment]
Understood, thanks!

**Comment by jeffhu1** [comment]
I'm having the same bug 
`interactive.py: error: the following arguments are required: data
`
how did you resolve it?

**Comment by gvskalyan** [comment]
Add `$DATAPATH` to the command.
DATAPATH is the same path given as destdir in preprocess.py or simple path where dictionaries after preprocess lie.
