### ISSUE TITLE
How does IWSLT EN-ZH calculate the bleu score?

### ISSUE THREAD

**Issue by Surnal** [bert-nmt/bert-nmt#51]
Hello, how do you calculate the bleu score about the results of Chinese sentences? Do you divide a sentence into words?

Looking forward to your reply, thank you very much.

@teslacool

**Comment by teslacool** [comment]
You can refer to this [file](https://github.com/bert-nmt/bert-nmt/blob/master/iwslt_interactive.sh) for more details.
