### ISSUE TITLE
AttributeError: 'BertTokenizerFast' object has no attribute 'encode_line'

### ISSUE THREAD

**Issue by ZhenHengDong** [bert-nmt/bert-nmt#53]
I encountered the following trouble: when I used a short corpus of Chinese and English to preprocess the data according to the command line as shown in the figure, there was an error. The wrong location is / root / Bert NMT / fairseq/ binarizer.py Line 60 of IDS= dict.encode_ Error in line():
AttributeError: 'BertTokenizerFast' object has no attribute 'encode_ line'.
![image](https://user-images.githubusercontent.com/62790827/104529238-3a407600-5644-11eb-814f-79e669a54143.png)

I don't know why there is such a mistake, because I use Chinese and English sentences, right? Looking forward to your reply. Thank you very much

**Comment by teslacool** [comment]
Can you try again with `transformers==3.5.0` and if the source language is Chinese, you should use a Bert model for Chinese rather than the above one for German.

**Comment by ZhenHengDong** [comment]
Thank you for your patience. Following your advice, I reduced the version of transfomers from 4.1.1 to 3.5.0 and successfully completed the data preprocessing task. Thank you again for your answer.

**Comment by omrastogi** [comment]
However when using transformers==3.5.0, I am getting - ImportError: cannot import name 'SAVE_STATE_WARNING' (https://github.com/bert-nmt/bert-nmt/issues/57). Which requires to revert to the latest version of transformers.
