### ISSUE TITLE
makedataforbert.sh doesn't run out of the box

### ISSUE THREAD

**Issue by shreyapandit** [bert-nmt/bert-nmt#7]
The bash makedataforbert.sh doesnt run out of the box

To reproduce,

Run  bash makedataforbert.sh  'fr-en.fr'

```
src lng fr-en.fr
sed: can't read train.fr-en.fr: No such file or directory
makedataforbert.sh: line 7: ../mosesdecoder/scripts/tokenizer/detokenizer.perl: No such file or directory
sed: can't read valid.fr-en.fr: No such file or directory
makedataforbert.sh: line 7: ../mosesdecoder/scripts/tokenizer/detokenizer.perl: No such file or directory
sed: can't read test.fr-en.fr: No such file or directory
makedataforbert.sh: line 7: ../mosesdecoder/scripts/tokenizer/detokenizer.perl: No such file or directory

```

The reason is that the previous steps downloads the files into the **translation/iwslt17.de_fr.en.bpe16k** folder instead of the same folder as the makedataforbert script.

**Comment by bert-nmt** [comment]
Yes. Before running this makedataforbert.sh, you should copy this file to right path.
