### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### ISSUE THREAD

**Issue by ecoli-hit** [bert-nmt/bert-nmt#71]
I'm fllowing the updata branch Train a BERT-fused NMT model but this error happened when strat training .
python 3.8
torch 1.5.0
transformers 3.5.0
gpu A100-40G
could you please help me out ?thx a lot

**Comment by shreyasaswar** [comment]
How did you solve this issue ?
