### ISSUE TITLE
transformer_s2_iwslt_de_en vs. transformer architecture

### ISSUE THREAD

**Issue by echan00** [bert-nmt/bert-nmt#9]
The BERT fused NMT-model uses `transformer_s2_iwslt_de_en` which seems to be the same as `transformer_iwslt_de_en`

Is it fair to assume using a larger model such as `transformer_s2_vaswani_wmt_en_de_big` would improve accuracy at the cost of requiring more resources and increasing training & inference time?

**Comment by bert-nmt** [comment]
We choose different architecture based on the size of the data set. 

For iwslt experiments, we choose `transformer_s2_iwslt_de_en`.
For wmt experiments, we choose `transformer_s2_vaswani_wmt_en_de_big`.

**Comment by echan00** [comment]
Thanks!
